// <auto-generated />
namespace SleekSoftMVCFramework.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateTbl_chnages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTbl_chnages));
        
        string IMigrationMetadata.Id
        {
            get { return "201712282007515_update-Tbl_chnages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
